services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
      - db
    restart: always

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Docker will manage this volume
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:  # This tells Docker to create and manage a volume
    driver: local

networks:
  app-network:
    driver: bridge